### ISSUE TITLE
[TODO #1] THIẾT KẾ ẤN PHẨM

### ISSUE THREAD

**Issue by QuachNgoc** [QuachNgoc/SocialMedia#1]
# Cần có:
- [x]  1 Blog cover cho trang Blog
- [x]  1 Event cover cho trang Event
- [x]  1 Forum cover cho trang Forum
- [x]  1 Poll cover cho trang Poll
- [x]  1 Cover mặc định cho user
- [ ]  1 Logo có 2 size: 200x200, 500x500
- [ ]  1 favicon có 2 size: 32x32, 16x16
- [x]  1 Trang nền chung cho Login

## LÀM NÀY XONG RỒI HÃY QUA TODO #2 NHA YANG :V
Hoàn Thành thì sẽ Close Issues này

**Comment by QuachNgoc** [comment]
[https://github.com/QuachNgoc/test](url)

**Comment by UIT20521262** [comment]
oke
https://drive.google.com/drive/folders/1PZrTBAdCmXEhtLIYasnLUBVcoeyBzpB8
