### ISSUE TITLE
[TODO #3] SỬA CÁC BUG VẶT + CHỈNH SỬA CÁC CHỨC NĂNG

### ISSUE THREAD

**Issue by QuachNgoc** [QuachNgoc/SocialMedia#3]
- [x] Thêm nút xóa bài Blog
- [ ] Thêm trang giới thiệu thành viên ở _creators
- [ ] Còn vài lỗi nữa nhiều quá nên chưa ghi vô :vv mé ơi. To be continue...
